"""empty message

Revision ID: 4bbfad69f2a5
Revises: 411ca6553f2a
Create Date: 2020-06-02 03:28:20.646663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bbfad69f2a5'
down_revision = '411ca6553f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website12', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website12')
    # ### end Alembic commands ###
