"""empty message

Revision ID: 71312f5c5a55
Revises: 4bbfad69f2a5
Create Date: 2020-06-02 05:58:06.763713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71312f5c5a55'
down_revision = '4bbfad69f2a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website12')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website12', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
