"""empty message

Revision ID: 812c93346335
Revises: 25988cef731c
Create Date: 2020-05-29 18:27:25.547802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812c93346335'
down_revision = '25988cef731c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('city1', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'city1')
    # ### end Alembic commands ###
