"""empty message

Revision ID: b5f92c46bfac
Revises: 090aceb131cf
Create Date: 2020-05-30 03:43:23.891763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f92c46bfac'
down_revision = '090aceb131cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website2', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website2')
    # ### end Alembic commands ###
